<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>
    <groupId>ec.mindalai</groupId>
    <artifactId>mindalai-management-jsf-web</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>mindalai-management-jsf-web - Platform Management JSF Web</name>
    <description>Frontend JSF Backoffice - consumidor HTTP/JSON de mindalai-management-api. JoinFaces 6.1.0, PrimeFaces, Harmony.</description>
    <modules>
        <module>management-jsf-app</module>
    </modules>
    <properties>
        <java.version>25</java.version>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <joinfaces.version>6.1.0</joinfaces.version>
        <primefaces.version>14.0.8</primefaces.version>
        <lombok.version>1.18.42</lombok.version>
    </properties>
</project>
